I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 44, in script call
    call addPoints(-5,'point_conviction','','bravo, tu n\'as rien compris','Bravo tu as bien compris !')
  File "game/functions.rpy", line 10, in script
    label addPoints(values = 0, key = '', condition = '', losemessage='', winmessage=''):
Exception: Could not find return label ('game/functions.rpy', 1686823489, 1).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 44, in script call
    call addPoints(-5,'point_conviction','','bravo, tu n\'as rien compris','Bravo tu as bien compris !')
  File "game/functions.rpy", line 10, in script
    label addPoints(values = 0, key = '', condition = '', losemessage='', winmessage=''):
  File "C:\Users\Informatique\Documents\renpy-8.0.3-sdk\renpy\ast.py", line 1782, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Informatique\Documents\renpy-8.0.3-sdk\renpy\execution.py", line 726, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/functions.rpy', 1686823489, 1).

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
OKDATA 1.0
Tue Jun 20 16:16:42 2023
